### ISSUE TITLE
Questions while writing new feature.

### ISSUE THREAD

**Issue by ezickler** [hpc/ior#21]
Hi,
i'm adding a new feature to IOR for benchmarking compression enabled filesystems. As IOR only can generate data which is uncompressible or super good to compress (repeating the data every 128bit).
Therefor other data is needed. 
My approach is to give the user the possibility to fill the buffer with his own data. As this also should be a bigger chunk of data to avoid to be to easy to compress an IO buffer of `transferSize` is not sufficient. My approach so far is to have an IO buffer of `blockSize`. Which then gives me the possibility to have different transfers and not only repeating the same. 
Also i want to keep to the IOR behavior as much as possible to make us of all the options. That's why i'm sticking to the transfer, blocksize, segment pattern.  So far so good.

Now the comes the problem / question. As the offset for the accesses are precomputed in the `offsetArray` there is no chance in `WriteOrReadSingle()` to get the according transfer as say aren't the same for every access now. Code wise i need offsets for the iobuffer to set before `backend->xfer()` happen. My question now is where i should save these offsets.
I would like to compute and store them in an additional column in the `offsetArray`.
But i'm not sure is this would interfere with anything else. Are there any objections on this?

Additionally i'm not sure if i understand the behavior of `GetOffsetArrayRandom()` correctly. Especially the `filePerProc` variant. For one file its doing the same as GetOffsetArray and mixing up everything in the end but for `filePerProc` there is this `if ((random() % test->numTasks) == pretendRank)`. I think this means not every transfer for every process is done but just 1/(numProc) in the mean. Is this correct on desired behavior?

In general is this the right way to communicate or is there any kind of dev mailing list for IOR? I think i will have some more questions and ideas while working on IOR and i would like to get them upstream here as there seams to be some active development here. 

Kind regards,
Enno

**Comment by glennklockwood** [comment]
> As the offset for the accesses are precomputed in the offsetArray there is no chance in WriteOrReadSingle() to get the according transfer as say aren't the same for every access now.

As you have discovered, IOR was not designed to read or write complex data, so you're going to have to make nontrivial changes to the way it performs its core I/O to make it do what you want.  I'm personally not enthusiastic about this since enabling IOR to perform arbitrarily complex reads and writes...

1. seems to only be useful when testing performance under compressibility (are there other use cases that would make it easier to expand the scope of IOR?)
2. would probably make it gnarlier to do read/write checking, and that code path is currently in flux (see #14)

But I would welcome opinions from other members of the IOR community on this.

That said, what you suggest sounds like a reasonable way of doing what you want.  I would have thought that there is already a `blockSize` buffer in memory, so creating a set of offset pointers into it seems like a reasonable way forward.

Regarding how `GetOffsetArrayRandom()` works, I know it does work for both fpp and shared file since I created a bunch of new I/O trace options in a fork of IOR using this routine a couple years ago.  But I would have to look carefully at the code again to explain exactly what's going on, which might take a few days to get to.

**Comment by johnbent** [comment]
I agree with Glenn.  This sounds like adding a lot of complexity to the
code-base for limited value.

This seems like you are proposing two different things:

1. Allow the user to fill the buffers with their own data
2. Change IOR so that the compressed buffers will have different sizes and
therefore the transfer sizes will be variable

The first seems easy.  The second seems overly complex and I don't
understand why it's needed.  If you're testing compression based
filesystems, then the filesystem is doing the compression and therefore IOR
transfer sizes will still always be the same size.

You also mention that the current transfer size can't be big enough.  Can't
you set it to be whatever you want?

Am I misunderstanding something here?

Do you want to test compression-based filesystems or do you want to use IOR
to mimic a compression-based filesystem by compressing the buffers before
sending them?  The first is easy with just allowing users to fill buffers
themselves.  The second seems really tough and I share Glenn's concerns.

John

**Comment by ezickler** [comment]
Thanks for your opinions and fast answers. 

To further clarification of my use case. I'm a graduate student at the university of Hamburg doing this as a project. Benchmarking compression is needed for new compression in Lustre which is in development here. First thought was to implement a new benchmark but inventing the wheel all over again might isn't necessary. Although doing things in IOR isn't especially  pleasant  as the documentation is rarely there and the code base is at least to me not the easy to ge through but IOR has many great things like AIORI and many options and features like like read write checking, hogging, memory and its a well known and used tool. So it seams attractive to reuse it. 
My view on your concerns:

> seems to only be useful when testing performance under compressibility (are there other use cases that would make it easier to expand the scope of IOR?)

I think there is much value in such a thing as compression becomes more and more a thing in data storage. But of course its to be discussed how important and if IOR is the right tool to benchmark such file systems.

> would probably make it gnarlier to do read/write checking, and that code path is currently in flux (see #14)

My goal is to keep read/write checking in a working condition, with as small changes as possible. What i have seen so far dosn't seams to hard, but i might be wrong.

> That said, what you suggest sounds like a reasonable way of doing what you want. I would have thought that there is already a blockSize buffer in memory, so creating a set of offset pointers into it seems like a reasonable way forward.

No. Looking at `XferBuffersSetup()` it's only possible to allocate buffers of `transferSize` right now. This makes  the `backend->xfer()` in `WriteOrReadsingle` easy as every buffer is the same and no offsetting is needed on the memory end of the calls. So this would be what i'm trying to add. Not only offseting the backend / file side but also the buffer side. 

> 2. Change IOR so that the compressed buffers will have different sizes and therefore the transfer sizes will be variable 
... The second seems overly complex and I don't understand why it's needed. If you're testing compression based filesystems, then the filesystem is doing the compression and therefore IOR transfer sizes will still always be the same size.

The transfer size variable per test in IOR and should stay this way as i think it's an important parameter for benchmarking (determine the IOPs count). I have no intend to have variable transferSizes in on single test. But as transferSize is an important parameter for i don't want to miss use it to have a a bigger buffer as it would keep these options unavailable for benchmarking compressing file systems. Although my plan is to do this with the `blocksize` this seams not to be as limiting the capabilities was much as as predetermined `transferSize`. 

As mention in the beginning i think the stat of documentation is in a bad place. For getting trough the code i set up a doxygen with call graphs and as sphinx documentation. I could try to document the parts i touch on my way trough. Is there any interests in having such things?
I chose doxygen for the doc generation from code comments an the call graph features and sphinx seams great as a higher level documentation for both devs and users. Both together could be uploaded to https://readthedocs.org/ an would be easily accessible. This would be great for  `GetOffsetArrayRandom()` thing for example.

**Comment by glennklockwood** [comment]
I agree that making a `bufferSize`-length buffer and a separate list of offsets within the buffer would probably be best for this approach.  `transferSize` can stay the same, as you pointed out.  My only major concern is that this code would be on the critical path of the benchmark, and we should be absolutely sure that the additional pointer chasing doesn't affect the measured I/O performance.  It shouldn't, but let's make sure.

Regarding documentation, Doxygen is not a bad idea.  I don't know how good of a job it will do between the front- and back-ends due to the way aioris are bound at runtime, but some documentation is better than none.

**Comment by ezickler** [comment]
Filed a PR #23 with my code. Did some refactoring and commenting in `GetOffsetArrayRandom`. I think now it's much clearer what is happening here

**Comment by JulianKunkel** [comment]
I consider that matter as closed. If there is something to discuss, please reopen.
