### ISSUE TITLE
Add aiori-libaio backend

### ISSUE THREAD

**Issue by adilger** [hpc/ior#240]
It would be useful to add a `libaio` backend (https://pagure.io/libaio) for IOR so that AIO/DIO performance can be evaluated.  The `libaio` interface is a non-POSIX asynchronous parallel IO submission engine that has existed in Linux for a long time (at least since 2002) and avoids a lot of overhead in the kernel w.r.t. buffer copies, page cache, etc.

Lustre 2.14 and later (and likely other filesystems of interest in HPC) has _optimized_ Linux AIO/DIO since v2_13_52 (commit https://github.com/lustre/lustre-release/commit/d1dded6e28 https://review.whamcloud.com/32416), but it has been functional (similar to normal read() write()) for a long time before that.  We've seen very good performance with AIO/DIO when testing with `fio`, but it would be good to get apples-to-apples comparisons with IOR as well.

I don't have a patch for this, but thought it would be a good start to file an issue to track it.

**Comment by carns** [comment]
Hi @adilger , will the same versions of Lustre also work with io_uring (i.e., liburing) if the kernel is new enough to support those system calls?  It's obviously not as widely available yet since it's only been the mainline kernel for a year or two, but it seems likely to have more traction in the long run as far as Linux-specific async I/O interfaces go.  Some background: https://kernel.dk/io_uring.pdf

**Comment by adilger** [comment]
Hi Phil, thanks for the link.  I've been watching a lot of traffic on the linux-fsdevel mailing list about it, so it definitely doesn't _seem_ like that code is finished. The performance is very competitive with SPDK, even though it is running in the kernel.

As yet, the Lustre client does not have hooks for io_uring. It was first added in the 5.1 or 5.2 kernel, which is ahead of what most systems have installed. It definitely seems like a good time to start adding support for it.  

It would be interesting if you know what, if any, applications/libraries are planning to use this interface?

**Comment by JulianKunkel** [comment]
Hi,
I had thought about an async backend in general, while this is generally
interesting,
an async backend doesn't really match what IOR/MDTest expects, i.e.,
synchronous IO in write/read calls.

App perspective to the AIORI interface is:
open()
write()
write()
write()
close()

There would be two approaches:
1) using the existing API, i.e. async inside one read/write call which
unlikely is better than doing blocking IO:
write() = queue IO, wait for completion.

2) breaking the API expectation, using async across read/writes, i.e., the
read/write returns before the actual IO is completed and queue it, that
would mean the example above would be effective:
open()
write = queue IO
write = queue IO
write = queue IO
close = wait for all pending IOs
Whereas once too many writes are queued, it would also wait for the pending
ones.

This wouldn't have merit for small IOs in MDTest.

For small IOs, this bears some potential from benchmarking perspective, is
that mode what you are looking for or is there something else?

**Comment by johnbent** [comment]
I suspect #2 would be the approach. And there’d be a queue depth parameter so each call to read/write would basically be:
Am I at QD yet?  If yes, wait. If not, queue another.

Maybe both a high and low water mark. So when you wait, you don’t necessarily wait to go to zero but just to the low water mark.

For mdtest with small files, you could presumably use the approach for the creates as well.

**Comment by adilger** [comment]
John, the typical usage would be to submit writes or reads until QD is reached. As each operation completes, it enqueues another operation to keep the pipeline full.  It only sleeps when QD is reached (async completions will keep it full) or when all of the work is all submitted and it waits for the queue to drain.  I don't think there would be a need for a minimum, since the goal would be to keep QD operations in flight.

Unfortunately, the Linux kernel does not yet allow parallel create operations within a single directory (though parallel name lookup is now available), so there is less benefit in having async operations for metadata at this point.  This can be worked around with Lustre by having multiple mountpoints on a single client, with a few threads per directory just to avoid any idle time, since the directory operations on the *server* are parallel.

**Comment by carns** [comment]
> It would be interesting if you know what, if any, applications/libraries are planning to use this interface?

FWIW my personal interest is in its potential for the backend implementation of storage services.  liburing is an appealing middle ground between SPDK and libaio in that context.  SPDK is a non-starter on production systems because it requires escalated privileges and/or a raw device.  libaio is worrisome because of it's tendency to fall back to unintended semantics instead of explicitly failing if your system (or workload scenario) doesn't support it.  liburing seems more designed to either do what it says on the tin or not. Anecdotally it is also faster than libaio, especially for small NVMe accesses. I've only tried it on my laptop, though, which is admittedly not a particularly relevant HPC platform to anyone but me :-)  I would guess that database or storage software vendors would be interested in it for the same reasons that I am, but that's just speculation on my part.

None of that really has much to do with IOR; I was mainly just interested in polling some opinions.  It's helpful to know that io_uring requires some degree of file system driver support.  I did not realize that.

FWIW it is worth noting that both libaio and liburing would be interesting from a performance perspective, but I also agree with the previous comments that it would require some thought in the context of IOR.  Trying to saturate a storage system with asynchronous operations is a departure from the normal IOR workload.

**Comment by adilger** [comment]
>  As yet, the Lustre client does not have hooks for io_uring. 

I think a more correct statement would have been "we haven't tested Lustre with io_uring, so there may (likely) be work needed for it to function correctly/optimally".  Since Lustre doesn't always do things the same way as a local disk filesystem, we may need to add/modify our driver to handle this new interface correctly.  There has been recent work to make libaio run very well on Lustre (https://jira.whamcloud.com/browse/LU-4198 and now https://jira.whamcloud.com/browse/LU-13799), that shows pretty clearly to me that there would be a significant benefit to changing applications/ libraries such as ADIO-lustre over to using async IO submission in the background if possible.

I think would likely transfer over to io_uring as well, but the devil is in the details.  I've filed https://jira.whamcloud.com/browse/LU-13801 to track the Lustre side of testing io_uring.

**Comment by JulianKunkel** [comment]
@adilger, feel free to have a go with the version provided in the branch.
As I state in the commit message, it is optimistic and should reveal the potential AIO has.
It reuses the same data buffer from IOR instead of copying the data as a real implementation must do and queues up and submits *granularity* many ops.
The last issued (up to granularity many) operations are executed upon close() (or (f)sync).
Two tuning options are provided to regulate the granularity and max ops in flight (check with -h).

**Comment by adilger** [comment]
@carns at least in preliminary testing, it looks like there is no need for changes to the Lustre client to use the `io_uring` engine for `fio` so long as the client is running a new enough kernel (e.g. Ubuntu 18.04/20.04 5.3 kernel) to provide this interface (for details see https://jira.whamcloud.com/browse/LU-13801).

**Comment by JulianKunkel** [comment]
That's good that liburing can be used as well. There's a AIO Backend in the
PR now:
https://github.com/hpc/ior/pull/243
Would be interested to see how that performs compared to regular non-async.
If it pays off a uring version wouldn't be a big of a deal.

**Comment by carns** [comment]
> @carns at least in preliminary testing, it looks like there is no need for changes to the Lustre client to use the `io_uring` engine for `fio` so long as the client is running a new enough kernel (e.g. Ubuntu 18.04/20.04 5.3 kernel) to provide this interface (for details see https://jira.whamcloud.com/browse/LU-13801).

Thanks Andreas!  I think I might have hijacked your github issue a bit with that tangent, but I'm happy to hear about this.

**Comment by JulianKunkel** [comment]
@adilger as there is now an aio backend, can this issue be closed?

**Comment by adilger** [comment]
Yes, issue can be closed. Thanks.
