### ISSUE TITLE
IOR should not use sparse files if not explicitly requested to do so

### ISSUE THREAD

**Issue by bolausson** [hpc/ior#261]
Hej,

I recently did run into a odd behaviour of a parallel file system (GPFS) when using IOR + direct IO + random offsets + stonewalling (Other parallel file systems might behave the same or different)

`srun --ntasks-per-node=4 -N 720 -n 2880 --exclusive dplace ior -r -w -e -g -b 4g -t 4096k -k -E -i 2 -z -D 180 --posix.odirect`

Assuming an empty directory, IOR has to create the file and it creates a 12 TB sparse file and does the read and write operations on that sparse file. This results in rates around 0.3 GB/s for both iterations which is utterly slow and will never write 12 TB in 180 seconds.

> $ ls -alsh testFile_pre-created testFile
> 148G -rw-rw----+ 1 userx xyz 12T Oct  9 18:07 testFile

If I run a sequential test before which creates a full, none sparse file, like the example below:
`srun --ntasks-per-node=4 -N 720 -n 2880 --exclusive dplace ior -r -w -e -g -b 4g -t 4096k -k -E -i 2`

> $ ls -alsh testFile_pre-created testFile
> 12T -rw-rw----+ 1 userx xyz 12T Oct  9 17:57 testFile

The results for a random, direct IO test on the existing file are different and are in the range of 40 GB/s (that's a factor of >100)

The same is true if I set the stonewall time high enough to let IOR write 12 TB at the slow rate of ~300 MB/s.
The first iteration will still show a throughput of around 300 MB/s but the second iteration shows the same result as if it would have been run against the pre-created file.

Example from a smaller test file:
```
access    bw(MiB/s)  IOPS       Latency(s)  block(KiB) xfer(KiB)  open(s)    wr/rd(s)   close(s)   total(s)   iter
------    ---------  ----       ----------  ---------- ---------  --------   --------   --------   --------   ----
write     326.53     81.63      34.04       512000     4096       0.000366   4410       0.001139   4410       0   
WARNING: Expected aggregate file size       = 1509949440000.
WARNING: Stat() of aggregate file size      = 1509949440000.
WARNING: Using actual aggregate bytes moved = 1435055947776.
WARNING: maybe caused by deadlineForStonewalling
read      59850      14963      0.169757    512000     4096       0.000205   22.87      0.000196   22.87      0   
write     49412      12353      0.193179    512000     4096       0.000331   29.14      0.000245   29.14      1   
WARNING: Expected aggregate file size       = 1509949440000.
WARNING: Stat() of aggregate file size      = 1509949440000.
WARNING: Using actual aggregate bytes moved = 1434565214208.
WARNING: maybe caused by deadlineForStonewalling
read      60604      15152      0.150210    512000     4096       0.000203   22.57      0.001170   22.57      1   
Max Write: 49412.45 MiB/sec (51812.71 MB/sec)
Max Read:  60604.41 MiB/sec (63548.33 MB/sec)
```

Since I can't come up with a real world scenario where an application is creating a huge sparse file and then reading or writing randomly to this sparse file (examples of applications doing this, or why this is a good thing to do are welcome), I would suggest that IOR should pre-create the target file(s) as fast as possible and then run the actual tests against those full pre-created, none sparse files. Like splitting up IOR tests in two phases. Adding a flag to to either not create sparse files or to explicitly create sparse files would help.

1. Pre create all files as fast as possible at full length (no matter if random or whatever evil has been chosen, just create the files as fast as possible)
2. Run actual test against the pre-created files

If there are existing files which have to be re-used, they need to be extended if they are to small (or delete and re-create). If the existing files are to large... you probably can just use them...

Cheers,
Bjoern

**Comment by JulianKunkel** [comment]
hi Bjoern,
thanks for submitting this issue. Could you provide additional information regarding the GPFS system such as:
- number of servers, their interconnect type/speed
- storage devices (SSDs?)
Thanks

**Comment by bolausson** [comment]
Storage is on 1440 HDDs and there are 8 NSD-Servers each with 2x EDR InfiniBand

Any thoughts on the sparse file and is there a reason it is done like it is now?

**Comment by JulianKunkel** [comment]
This is interesting, as far as I know, the reported behavior only applies
to GPFS and it isn't a general problem of the pattern.
I also agree that the end product of a file produced by a sane application
normally won't be that much sparse but that is the price to pay when using
stonewalling with a random pattern.
There are some formats that are sparse to some extend, for example, BP from
ADIOS at some point created one contiguous region per process but with a
hole between the regions of different processes.
When we talk about 1000 processes maybe they will behave like random,
though.

With 4 MB transfer size and that configuration, I would agree that 40 GiB/s
is more the expected performance. It may have to do with the way block
allocation is done by GPFS.
I have seen that GPFS handles some pattern suboptimally cause it wasn't
designed for them. Maybe it is one of those. That could be investigated
with IBM.

I would also agree, if that is a design choice or bug in GPFS, a workaround
would be to pre-create the file. To measure the effective performance an
application would see, this pre-creation must be included in the
performance measurement. This, in turn renders the benefit of stonewalling
obsolete. In that sense, maybe running without stone walling and a
pre-defined data set is suitable. If you could follow up with IBM, it would
be great. Otherwise, no problem to add a "prefilling" option that would be
included in the timing and primarily meaningful in non-stone walling tests.

**Comment by bolausson** [comment]
We are in contact with IBM so lets see if we get an answer for this behaviour. I will update this thread once I know more.

Adding an option to pre-fill the files would be great.

**Comment by adilger** [comment]
IOR is typically simulating a shared single file workload where strided writes/reads eventually result in a densely-allocated file (i.e. each thread is writing to offset `(rank + N) x chunk_size`), even though there is an intermediate state when there are holes in the file.  I think there are some workloads that benefit from sparse random writes (e.g. ad-hoc database files, sparse matrix/grid files), and definitely from random reads, so I think the need to preallocate files is a workload-specific decision.  Since `fallocate()` is relatively widely supported these days (on Linux at least, `posix_fallocate()` on non-Linux), it probably makes sense to have an option to use this pre-allocate the files to see what effect this has on performance.

**Comment by pramodk** [comment]
I have been working with @bolausson on this issue. I just want to add information about `posix_fallocate` / `fallocate`: 

> Since fallocate() is relatively widely supported these days (on Linux at least, posix_fallocate() on non-Linux), it probably makes sense to have an option to use this pre-allocate the files to see what effect this has on performance.

I was thinking the same and wanted to do PR here! To test this, I started with pre-creating file with `fallocate` where `du -h` or `ls -alsh` shows file as fully allocated (12TB). But, when I run same random I/O tests described above, I **got same performance as sparse file**. So I am not sure `posix_fallocate ` will help here and hence didn't spend efforts to implement the same in IOR.

If anyone has better suggestions to test this, let me know!

**Comment by JulianKunkel** [comment]
Nice try. From this information, I would strongly advise discussing with
IBM about GPFS.
They could implement fallocate() if it is beneficial. There shouldn't be
the need to prefill the bytes manually as this is why the call is there.

**Comment by wszoecs** [comment]
The behavior - where for example "IOR -F -w -z -t 4k -b 500g" is extremely slow due to sparse writes - happens on Lustre too.
The random-writes are slow - until you wrote to enough offsets - so that the file becomes non-sparse.
Writing with '-z' to previously created files (without truncating them) is significantly faster.
So "-b 4g"  produces way higher IOPS counts - than for example "-b 768g" (with otherwise identical options) - as in the later case - it takes basically forever for the output file to become non-sparse.

**Comment by JulianKunkel** [comment]
Would you say that the random benchmark should offer to include the
pre-allocation into the benchmark?
I don't see any issue implementing this *but* for the new way of dealing
with random. It could be that it writes the whole blocksize, then ranomize
access,
then repeat this.

**Comment by wszoecs** [comment]
it DEPENDS ... - mainly - "what exactly do we want to benchmark".

If we want, that randomly writing to sparse-files should be 'the benchmark', then no need to pre-allocate.
But then - we have a huge dependency with the filesize (-b option) - because the larger that gets, the slower it gets.
(so -b 1g is way faster than -b 10g or even -b 100g)

If we assume, that random-writes to existing files (non-sparse) should be 'the benchmark' - then it needs to change.
Pre-allocating all blocks first non-timed - could be a solution - but depending on fpp/shared-file and -b XXX - this could take quite a while...

**Comment by JulianKunkel** [comment]
I think both are valid benchmarks. If the file is not sparse at the end,
users could decide to pre-allocate blocks - if faster - but this should be
part of the runtime.

**Comment by glennklockwood** [comment]
> I think both are valid benchmarks.

I agree; we do it both ways.  Highest priority should be to preserve the same general performance expectation as the previous `-z` if possible so that naive users get approximately the same performance with this new version.

Having sparse file support as an option is also desirable to illustrate the sparse file penalty.  However we have a few acceptance tests coming up that explicitly accesses to a pre-allocated file.

**Comment by JulianKunkel** [comment]
There is now a first fix in the #270 branch.

**Comment by JulianKunkel** [comment]
I've now completed a fix for this. In either way, the write pattern is the same as for sequential write.

There are two modes:
1) without stonewall the file is filled before any random IO is done. With verbose > 1, the runtime costs for this are printed. 
Example:
$ mpiexec -np 2 ./src/ior  --randomPrefill=1m -b 2m -z -s 4  -v -v 
2) with stonewall, every time a new segment is approached, all processes coordinate and pre-fill/write the data for the current segment, then doing their random IO.
It is apparent that the synchronization comes with a cost (which is again printed using -v -v).
Example usage:
$ mpiexec -np 2 ./src/ior  --randomPrefill=1m -b 2m -z -s 4 -D1 -v -v 

This can be particularly useful if a medium size blocksize is used for random IO but many segments say:
$ mpiexec -np 2 ./src/ior  --randomPrefill=10m -b 1000m -t4k -z -s 1000 -D1 -v -v 

Maybe someone here likes to test the performance implications for Lustre?

**Comment by bolausson** [comment]
As soon as I have access to a proper system, I can put it to the test, but I can't predict when this will be (most likely not this year).

**Comment by JulianKunkel** [comment]
@bolausson any feedback? I reckon, we can close this issue.

**Comment by bolausson** [comment]
Hello Julian,

I have not had the chance to test this, but yes, lets close this topic.
