### ISSUE TITLE
read bandwidth cache effects 

### ISSUE THREAD

**Issue by wadudmiah** [hpc/ior#328]
Hi, 

I am getting much higher read bandwidth and write bandwidth on a single compute node with GPFS probably due to cache effects:
```
Max Write: 6013.25 MiB/sec (6305.34 MB/sec)
Max Read:  11667.90 MiB/sec (12234.68 MB/sec)
```
In my IOR configuration file, I have put `reorderTasksConstant=1`, so can't understand why there is such a big difference in bandwidth. Attached is my full configuration file. 

Thanks in advance.

[run1.txt](https://github.com/hpc/ior/files/5934149/run1.txt)

**Comment by wadudmiah** [comment]
If I run on the command line:
```
mpirun -n 64 ./ior -t 1m -b 16m -s 16 -F -C
```
I get more realistic read bandwidth
```
Max Write: 6018.64 MiB/sec (6311.00 MB/sec)
Max Read:  5968.43 MiB/sec (6258.35 MB/sec)
```

**Comment by JulianKunkel** [comment]
To understand this better, what did you run to obtain the first results. And on how many nodes were either of the results?

**Comment by carns** [comment]
Hi @wadudmiah, for this test I'm guessing that the GPFS client side cache is the biggest factor, and that is done per node (in the kernel) rather than per process.  So you won't be able to combat caching with any command line options in a single node test.

One other minor note: I don't think it is happening here because your block size is much bigger than your transfer size, but generally speaking the task reordering might not work when collective I/O (`collective=1`) is used too, if your MPI-IO implementation elects to use collective buffering and aggregators.  The task reordering will alter which ranks issue I/O for a given part of the file, but I don't think it will alter which ranks are chosen by MPI-IO to be aggregators (and thus which ranks benefit from caching).  Again probably not an issue here (I'm guessing collective buffering won't automatically kick in unless you have more interleaving of access between ranks),  just pointing it out.  For this example the single node thing is my guess.

**Comment by wadudmiah** [comment]
@JulianKunkel This is on a single node run. 

@carns Do you once that I run the benchmark on multiple nodes, this will not be an issue anymore? I would like to get the configuration correct before I do long multiple benchmark runs. 

Thanks everyone.

**Comment by JulianKunkel** [comment]
The reorderTasksConstant=1 is only helpful if you have processes running on multiple nodes as cache is assigned per node. So, yes, you should use two nodes at least for proper benchmarking.

**Comment by wadudmiah** [comment]
As a general rule, how many processes per node should I use? I have 40 CPU cores per node.

**Comment by JulianKunkel** [comment]
Tricky. GPFS obtains good results with just a few procs per node. I'd try with a number between 4 - 10 and see if the result is close to network bandwidth. Having too many can be problematic due to stragglers.

**Comment by wadudmiah** [comment]
Thanks for your help everyone!
