### ISSUE TITLE
Random IOPS test results are  far away from iozone and vdbench

### ISSUE THREAD

**Issue by louiscaocao** [hpc/ior#356]
Dears,
When I do RANDOM IOPS test for a lustre file system with IOR 3.3.0 . I found that the IOPS load always went down slowly. In my testing, from 150K IOPS go down to 46K IOPS within 10 minutes. In the same situation, Vedbench and Iozone can keep Random IOPS load to about 90K，and during the whole process we can observed IO wait by using top command .
But, for the IOR we observed IO wait went down for about 50 to zero every time.

It looks like IOR cann't provide a continuous high randon IOPS load.

Any response is appreciated

B. R.
Louis Cao
caojf6@163.com

**Comment by JulianKunkel** [comment]
Hi, interesting, that shouldn't be the case. Can you post the exact run parameters for ior?

**Comment by louiscaocao** [comment]
> Hi, interesting, that shouldn't be the case. Can you post the exact run parameters for ior?
Hi，here is my commond.
mpirun --allow-run-as-root --oversubscribe -np 128 -hostfile node4 --map-by node ior -b 8G -t 4k -w -r -F -z -o /lustre/iortest/data/ior-test.file

**Comment by JulianKunkel** [comment]
I thought a bit about the issue. Let me recapitulate what happens in this version for write:
Each process has an 8 GByte area, all the possible 4k offsets are shuffled and written exactly once.
All processes operate independently. Once a process completed its IO, it stops and waits for the others.

Since you used -F, each process works on another file, depending on your Lustre stripe setting. I assume you may have used a stripe of 1? 
It is to be expected that different processes will proceed with different speeds, hence the number of procs doing IO will decrease over time.
Can it be that 10 min runtime is closer to the end, where some processes already finished?

I assume you run iozone as a single process on one node with a number of threads, what stripe count did you use?
Did you use iozone throughput mode running on 1 file per thread (similar to -F of ior).
iozone by default uses stonewalling, hence all the processes will stop at the same time (except if you use -x). This behavior can also be recreated with ior, e.g., using -D=100 (100 second stonewall).

I assume that stonewall is enabled for iozone but not for ior and at 10 min most of the procs of IOR are done. Hence, the behavior cannot be compared. If you add -D=300 (or longer if you increase -b accordingly), then I expect you'll see a comparable result.

**Comment by louiscaocao** [comment]
Hi, JulianKunkel,
Thank you for your replay.  There are 8 OSTs in my lustre system. I haved tested Random IOPS with stripe=8. That resulted to a smaller slope not a stable IOPS rate.

**Comment by louiscaocao** [comment]
![Screenshot_20210331_170750](https://user-images.githubusercontent.com/76481265/113120131-d80b1080-9243-11eb-8701-241a88fdc6c3.jpg)
![Screenshot_20210331_170836](https://user-images.githubusercontent.com/76481265/113120115-d3def300-9243-11eb-943b-4034b38a0db5.jpg)
![Uploading Screenshot_20210331_170724.jpg…]()

**Comment by louiscaocao** [comment]
![Uploading Screenshot_20210331_170724.jpg…]()

**Comment by JulianKunkel** [comment]
I suppose that it really could be a straggler effect.
Please try to run with -D=100 or try (if you like to measure for 600s) on a single bigger file:
mpirun --allow-run-as-root --oversubscribe -np 128 -hostfile node4 --map-by node ior -b 32G -D=600 -t 4k -w -r -z -o /lustre/iortest/data/ior-test.file

**Comment by louiscaocao** [comment]
> I thought a bit about the issue. Let me recapitulate what happens in this version for write:
> Each process has an 8 GByte area, all the possible 4k offsets are shuffled and written exactly once.
> All processes operate independently. Once a process completed its IO, it stops and waits for the others.
> 
> Since you used -F, each process works on another file, depending on your Lustre stripe setting. I assume you may have used a stripe of 1?
> It is to be expected that different processes will proceed with different speeds, hence the number of procs doing IO will decrease over time.
> Can it be that 10 min runtime is closer to the end, where some processes already finished?
> 
> I assume you run iozone as a single process on one node with a number of threads, what stripe count did you use?
> Did you use iozone throughput mode running on 1 file per thread (similar to -F of ior).
> iozone by default uses stonewalling, hence all the processes will stop at the same time (except if you use -x). This behavior can also be recreated with ior, e.g., using -D=100 (100 second stonewall).
> 
> I assume that stonewall is enabled for iozone but not for ior and at 10 min most of the procs of IOR are done. Hence, the behavior cannot be compared. If you add -D=300 (or longer if you increase -b accordingly), then I expect you'll see a comparable result.

Dear JulianKunkel,
As above my descripation, I want to know why there are no IO load when I do random IOPS test with IOR. Even I used 4 clients and 256 processes, the IO wait goes to 0 within  few minutes.

**Comment by louiscaocao** [comment]
> I suppose that it really could be a straggler effect.
> Please try to run with -D=100 or try (if you like to measure for 600s) on a single bigger file:
> mpirun --allow-run-as-root --oversubscribe -np 128 -hostfile node4 --map-by node ior -b 32G -D=600 -t 4k -w -r -z -o /lustre/iortest/data/ior-test.file

OK. I will try.

**Comment by JulianKunkel** [comment]
Out of personal curiosity (and motivated by issues with the IO500), why is a 4k random workload so relevant to you? (Thank you for your help there)

**Comment by louiscaocao** [comment]
> Out of personal curiosity (and motivated by issues with the IO500), why is a 4k random workload so relevant to you? (Thank you for your help there)

I am a tester of HPC solutions.  It always confused me , when I did  RANDOM IOPS performance evaluation by using IOR. The test cases always runing several days and cound't be finished. At the same time Vdbench and iozone perform faster.
But Vdbench and iozone cann't run with mpi, are applicable to HPC.

**Comment by JulianKunkel** [comment]
I somehow lost track last year of this issue, is this now somehow resolved? There had been some reworks of the random I/O path. In my testing performance appears to be reasonable. 
I suppose the answer is that $ iozone on a single node behaves differently than the parallel I/O.
It seems to be a good idea though to compare the performance of different benchmarks just for sanity.
