### ISSUE TITLE
Support option to drop testFile from cache before read

### ISSUE THREAD

**Issue by parkeraddison** [hpc/ior#370]
During I/O benchmarking, local caching has a large effect on read performance -- this comes into play when performing multiple repetitions of a test on the same existing file, or when read after writing on a single node.

One solution could be to drop the testFile from the page cache before reading. This still preserves caching overhead (which I think is important to capture in realistic benchmarking), and works with MPI-IO.

Currently I have a shell script which uses `dd` to drop the file from the cache before running each IOR read test. Here's a minimal example:
```sh
ior -w -k -b 64m  # Create the file, larger for demonstration purposes
ior -a MPIIO -r -k -E -b 64m  # Note the high read performance -- file is in cache

dd of=testFile oflag=nocache conv=notrunc,fdatasync count=0  # Ensure drop from cache
ior -a MPIIO -r -k -E -b 64m  # Note the realistic read performance
```
It appears to work -- a subsequent cache-clearing and read test on the same existing file maintains a similar bandwidth, rather than skyrocketing which was the typical sign of local caching.

Would it be possible to add this sort of cache-droppping-before-read functionality to IOR as an option?

Here are some of the resources I came across:
- [Drop a specific file from the Linux filesystem cache?](https://unix.stackexchange.com/a/162806)
- [posix_fadvise(2) — Linux manual page](https://man7.org/linux/man-pages/man2/posix_fadvise.2.html)

**Comment by glennklockwood** [comment]
The easiest way to do this may be extending #351 to IOR and letting the end user do a prologue/epilogue between successive runs.

Alternatively, the [IOR documentation discusses how to do this with posix_fadvise](https://ior.readthedocs.io/en/latest/userDoc/tutorial.html#defeating-page-cache), but because that is only a hint, there's no guarantee the kernel will honor the request and the results produced by IOR become nondeterministic.

Most people typically use `-C` to work around this particular problem; is there a reason that won't work for what you're trying to accomplish?

**Comment by parkeraddison** [comment]
Ah yes a prologue/epilogue would be perfect for this.

I'm mostly interested in this for single-node tests where -C has no effect, or for multi-node tests with repetitions. I suppose multi-node tests with repetitions can make use of -Z (random task reordering) so that a node doesn't keep reading the same chunk of the file each repetition?

**Comment by adilger** [comment]
The `memoryPerNode` parameter (e.g. `-M 50%`) in the IOR documentation Glenn linked would appear to do this even for a single node configuration?

**Comment by JulianKunkel** [comment]
Will close this issue. I believe in the memoryPerNode parameter.
