### ISSUE TITLE
write + checkWrite fails without also enabling read

### ISSUE THREAD

**Issue by adammoody** [hpc/ior#55]
The following command line does a write + writeCheck:

srun -N2 -n4 ./install/bin/ior -a MPIIO -b 10MB -t 1MB -v -F -w -W -o /path/to/foo

This fails with access errors while trying to read the file during the checkWrite phase which was opened as WRONLY:

Improper use of FILE Mode, Using WRONLY for Read!

If I also add a -r to the command line to force a read test, then the file is opened in RDWR mode and the checkWrite passes.

Is this expected behavior, or should the file always be opened as RDWR with -w -W?

**Comment by glennklockwood** [comment]
This is not intentional.  A lot of the file open permissions got broken when non-POSIX aioris (S3, HDFS) were added a few years back, and this is almost definitely another victim.

Ideally WRONLY would be used in the absence of `-W`, but RDWR if `-w -W` are specified.

**Comment by adammoody** [comment]
The related code is in CheckRunSettings in src/parse_optons.c:

https://github.com/hpc/ior/blob/master/src/parse_options.c#L116

**Comment by johnbent** [comment]
Is this a more fundamental question of whether to use the same file handle to both write and then read check?  O_RDWR makes writes much slower in many file systems.  Perhaps we should close the O_WRONLY handle and then reopen with O_RDONLY to do the check.  Do we verify immediately after each write or in a big verify phase after the write phase?  Is the former even something that is an interesting useful test?

**Comment by glennklockwood** [comment]
I would have initially guessed that a different file handle was used to do the verification step too.  However this introduces some potentially weird behavior on not-strictly-POSIX file systems because the `close()` (or lack of one) can affect consistency.

We could define this exact behavior as an option, but it’s starting to get messy.  I am inclined to leave the default behavior as-is (recycle the file handle on verify) to have the best chance at not failing due to known consistency limitations for the underlying storage system.

**Comment by adammoody** [comment]
If you'd like to keep the single file handle for now, this PR should help:
https://github.com/hpc/ior/pull/56
